language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 7
  - hhvm
  - hhvm-nightly
  
matrix:
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

install: composer install --dev --no-interaction

before_script:
  - mysql -e 'create database pinq_demo;'

script:
 - phpunit --configuration "phpunit.xml.dist"

after_script:
 - php vendor/bin/coveralls -v
